version: '3.8'
services:

  webmail-server: 
    image: roundcube/roundcubemail:1.4.x-apache
    container_name: webmail-server
    hostname: ${WEBMAIL_HOSTNAME}
    ports: 
      - "${WEBMAIL_PORT}:80"
    networks:
      mail_network:
        aliases:
          - ${WEBMAIL_HOSTNAME}
    environment: 
      - ROUNDCUBEMAIL_DEFAULT_HOST=${IMAP_SERVER_HOSTNAME}
      - ROUNDCUBEMAIL_DEFAULT_PORT=${IMAP_SERVER_PORT} 
      - ROUNDCUBEMAIL_SMTP_SERVER=${SMTP_SERVER_HOSTNAME} 
      - ROUNDCUBEMAIL_SMTP_PORT=${SMTP_SERVER_PORT} 
    healthcheck:
      test: ["CMD", "curl", "-f", "http://${WEBMAIL_HOSTNAME}"]
      interval: 5s
      timeout: 3s
      retries: 3
      start_period: 3s


  mail-server:
    build: ./docker/greenmail-healthcheck
    container_name: mail-server
    hostname: ${MAIL_SERVER_HOSTNAME}
    ports:
      - "3110:3110"
      - "${SMTP_SERVER_PORT}:3025"
      - "${IMAP_SERVER_PORT}:3143"
      - "3465:3465"
      - "3993:3993"
      - "3995:3995" 
    networks:
      mail_network:
        aliases:
          - ${MAIL_SERVER_HOSTNAME}
          - ${SMTP_SERVER_HOSTNAME}
          - ${IMAP_SERVER_HOSTNAME}
    healthcheck:
      test: "nc -z localhost 3025 && nc -z localhost 3143"
      interval: 5s
      timeout: 3s
      retries: 3
      start_period: 3s


networks:
  mail_network:
    driver: bridge



