version: '2.4'
services:

  webmail-server: 
    image: roundcube/roundcubemail
    container_name: webmail-server
    hostname: ${WEBMAIL_HOSTNAME}
    ports: 
      - "8000:80"
    networks:
      mail_network:
        aliases:
          - ${WEBMAIL_HOSTNAME}
    environment: 
      - ROUNDCUBEMAIL_DEFAULT_HOST=${IMAP_SERVER_HOSTNAME}
      - ROUNDCUBEMAIL_DEFAULT_PORT=${IMAP_SERVER_PORT} 
      - ROUNDCUBEMAIL_SMTP_SERVER=${SMTP_SERVER_HOSTNAME} 
      - ROUNDCUBEMAIL_SMTP_PORT=${SMTP_SERVER_PORT} 


  mail-server:
    image: greenmail/standalone
    container_name: mail-server
    hostname: ${MAIL_SERVER_HOSTNAME}
    ports:
      - "3110:3110"
      - "${SMTP_SERVER_PORT}:3025"
      - "${IMAP_SERVER_PORT}:3143"
      - "3465:3465"
      - "3993:3993"
      - "3995:3995" 
    networks:
      mail_network:
        aliases:
          - ${MAIL_SERVER_HOSTNAME}
          - ${SMTP_SERVER_HOSTNAME}
          - ${IMAP_SERVER_HOSTNAME}

networks:
  mail_network:
    driver: bridge



