version: '3.8'
services:

  webmail-server: 
    image: roundcube/roundcubemail:1.5.x-apache
    container_name: webmail-server
    hostname: webmail.docker
    ports: 
      - "${WEBMAIL_PORT}:80"
    networks:
      mail_network:
        aliases:
          - webmail.docker
    environment: 
      - ROUNDCUBEMAIL_DEFAULT_HOST=mail.docker
      - ROUNDCUBEMAIL_DEFAULT_PORT=3143
      - ROUNDCUBEMAIL_SMTP_SERVER=mail.docker 
      - ROUNDCUBEMAIL_SMTP_PORT=3025
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost"]
      interval: 5s
      timeout: 3s
      retries: 3
      start_period: 3s


  mail-server:
    build: ./docker/greenmail-healthcheck
    container_name: mail-server
    hostname: mail.docker
    ports:
      - "${POP3_SERVER_PORT}:3110"
      - "${SMTP_SERVER_PORT}:3025"
      - "${IMAP_SERVER_PORT}:3143"
      - "${IMAPS_SERVER_PORT}:3993"
      - "${SMTPS_SERVER_PORT}:3465"
      - "${POP3S_SERVER_PORT}:3995"
    networks:
      mail_network:
        aliases:
          - mail.docker
          - smtp.docker
          - imap.docker
    healthcheck:
      test: "nc -z localhost 3025 && nc -z localhost 3143"
      interval: 5s
      timeout: 3s
      retries: 3
      start_period: 3s


networks:
  mail_network:
    driver: bridge



